export const HIGH_SCHOOL_SUBJECTS = [
  // Compulsory (8-4-4 & CBC)
  "Mathematics",
  "English Language",
  "Kiswahili",
  // Sciences
  "Biology",
  "Chemistry",
  "Physics",
  // Humanities
  "History and Government",
  "Geography",
  "Christian Religious Education",
  "Islamic Religious Education",
  "Hindu Religious Education",
  // Applied & Technical
  "Business Studies",
  "Economics",
  "Agriculture",
  "Computer Studies",
  "Computer Science",
  "Home Science",
  "Aviation Technology",
  "Building and Construction",
  "Electricity",
  "Drawing and Design",
  "Metal Work",
  "Wood Work",
  "Power Mechanics",
  // Creative & Practical Arts
  "Art and Design",
  "Music",
  // Languages
  "French",
  "German",
  "Arabic",
  "Fasihi ya Kiswahili",
  "Literature in English",
  "Kenya Sign Language",
  // Others
  "Physical Education",
  "Sports Science",
  "Entrepreneurship Education"
];

export const UNIVERSITY_SUBJECTS = [
  // Mathematics & Statistics
  "Calculus and Analysis",
  "Linear Algebra",
  "Statistics and Probability",
  "Discrete Mathematics",
  "Engineering Mathematics",
  "Numerical Methods",
  "Actuarial Science",
  // Physical & Biological Sciences
  "Physics",
  "Chemistry",
  "Analytical Chemistry",
  "Industrial Chemistry",
  "Biology",
  "Biochemistry",
  "Microbiology and Biotechnology",
  "Zoology",
  "Botany and Plant Sciences",
  "Environmental Science",
  "Ecology and Conservation",
  "Geology",
  "Meteorology",
  "Fisheries and Aquatic Sciences",
  "Forestry and Wildlife Management",
  // Computing, ICT & Data Science
  "Computer Science Fundamentals",
  "Information Technology",
  "Data Science",
  "Programming — Python",
  "Programming — Java",
  "Programming — C and C++",
  "Programming — JavaScript",
  "Data Structures and Algorithms",
  "Database Management Systems",
  "Computer Networks",
  "Cyber Security",
  "Artificial Intelligence",
  "Machine Learning",
  "Software Engineering",
  "Web Development",
  "Mobile App Development",
  "Operating Systems",
  // Engineering, Technology & Built Environment
  "Civil Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Chemical Engineering",
  "Environmental Engineering",
  "Structural Engineering",
  "Petroleum Engineering",
  "Mining and Mineral Processing Engineering",
  "Geospatial Engineering",
  "Aeronautical Engineering",
  "Agricultural and Biosystems Engineering",
  "Telecommunications Engineering",
  "Architecture and Design",
  "Quantity Surveying",
  "Construction Management",
  "Urban and Regional Planning",
  // Business, Finance & Economics
  "Accounting Principles",
  "Financial Accounting",
  "Management Accounting",
  "Corporate Finance",
  "Banking and Finance",
  "Insurance and Risk Management",
  "Taxation",
  "Procurement and Supply Chain Management",
  "Logistics and Transport Management",
  "Project Management",
  "Real Estate and Land Economics",
  "Economics Microeconomics",
  "Economics Macroeconomics",
  "Development Economics",
  "Business Management",
  "Marketing Management",
  "Human Resource Management",
  "Entrepreneurship",
  // Law
  "Commercial Law",
  "Constitutional Law",
  "Criminal Law",
  "Civil Law",
  "Land Law",
  "Family Law",
  // Medicine, Nursing & Health Sciences
  "Medicine and Surgery",
  "Anatomy and Physiology",
  "Pharmacology",
  "Nursing Science",
  "Clinical Medicine",
  "Medical Laboratory Science",
  "Radiography and Medical Imaging",
  "Physiotherapy",
  "Occupational Therapy",
  "Optometry and Vision Science",
  "Dental Technology",
  "Public Health",
  "Community Health",
  "Health Records and Information Management",
  "Pharmacy",
  "Dentistry",
  "Nutrition and Dietetics",
  // Agriculture, Food & Veterinary
  "Agriculture Science",
  "Agribusiness Management",
  "Crop Science",
  "Soil Science",
  "Animal Husbandry",
  "Food Science and Technology",
  "Horticulture",
  "Veterinary Medicine",
  // Social Sciences & Humanities
  "Psychology",
  "Guidance and Counselling",
  "Sociology",
  "Anthropology",
  "Political Science",
  "International Relations",
  "Public Administration and Governance",
  "Criminology and Security Studies",
  "Development Studies",
  "Gender and Development Studies",
  "Peace and Conflict Studies",
  "Philosophy",
  "Religious Studies",
  "Linguistics and Languages",
  "Kiswahili Studies",
  // Education
  "Education Theory",
  "Special Needs Education",
  "Early Childhood Development Education",
  "Curriculum Development",
  "Sports Science and Recreation",
  // Media, Information & Communication
  "Journalism and Mass Communication",
  "Public Relations",
  "Film and Media Studies",
  "Records Management and Information Science",
  "Library and Information Science",
  // Hospitality, Tourism & Design
  "Tourism and Hospitality",
  "Hotel Management",
  "Fashion and Design",
  "Graphic Communication Design",
  "Animation and Game Design",
  "Fine Art",
  "Performing Arts"
];

export const EDUCATIONAL_SUBJECTS = {
  HIGH_SCHOOL: HIGH_SCHOOL_SUBJECTS,
  UNIVERSITY: UNIVERSITY_SUBJECTS,
};

export function getSubjectsByLevel(level?: string) {
  if (level?.toUpperCase().includes("UNIVERSITY")) {
    return UNIVERSITY_SUBJECTS;
  }
  return HIGH_SCHOOL_SUBJECTS;
}
