export const HIGH_SCHOOL_SUBJECTS = [
  "Mathematics",
  "English Language",
  "Kiswahili",
  "Biology",
  "Chemistry",
  "Physics",
  "History and Government",
  "Geography",
  "Christian Religious Education",
  "Islamic Religious Education",
  "Hindu Religious Education",
  "Business Studies",
  "Economics",
  "Agriculture",
  "Computer Studies",
  "Home Science",
  "Art and Design",
  "Music",
  "French",
  "German",
  "Arabic",
  "Fasihi ya Kiswahili",
  "Literature in English",
  "Aviation Technology",
  "Building and Construction",
  "Electricity",
  "Drawing and Design",
  "Metal Work",
  "Wood Work",
  "Power Mechanics",
  "Physical Education",
  "Kenya Sign Language"
];

export const UNIVERSITY_SUBJECTS = [
  "Calculus and Analysis",
  "Linear Algebra",
  "Statistics and Probability",
  "Discrete Mathematics",
  "Engineering Mathematics",
  "Numerical Methods",
  "Physics",
  "Chemistry",
  "Biology",
  "Biochemistry",
  "Computer Science Fundamentals",
  "Programming — Python",
  "Programming — Java",
  "Programming — C and C++",
  "Programming — JavaScript",
  "Data Structures and Algorithms",
  "Database Management Systems",
  "Computer Networks",
  "Cyber Security",
  "Artificial Intelligence",
  "Machine Learning",
  "Software Engineering",
  "Web Development",
  "Mobile App Development",
  "Operating Systems",
  "Accounting Principles",
  "Financial Accounting",
  "Management Accounting",
  "Corporate Finance",
  "Economics Microeconomics",
  "Economics Macroeconomics",
  "Business Management",
  "Marketing Management",
  "Human Resource Management",
  "Entrepreneurship",
  "Commercial Law",
  "Constitutional Law",
  "Criminal Law",
  "Civil Law",
  "Land Law",
  "Family Law",
  "Medicine and Surgery",
  "Anatomy and Physiology",
  "Pharmacology",
  "Nursing Science",
  "Public Health",
  "Pharmacy",
  "Dentistry",
  "Architecture and Design",
  "Civil Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Chemical Engineering",
  "Environmental Engineering",
  "Structural Engineering",
  "Environmental Science",
  "Ecology and Conservation",
  "Geology",
  "Meteorology",
  "Psychology",
  "Sociology",
  "Political Science",
  "International Relations",
  "Philosophy",
  "Religious Studies",
  "Education Theory",
  "Curriculum Development",
  "Journalism and Mass Communication",
  "Public Relations",
  "Film and Media Studies",
  "Social Work",
  "Community Development",
  "Agriculture Science",
  "Animal Husbandry",
  "Food Science and Technology",
  "Horticulture",
  "Veterinary Medicine",
  "Tourism and Hospitality",
  "Hotel Management",
  "Nutrition and Dietetics",
  "Fashion and Design",
  "Fine Art",
  "Performing Arts"
];

export const EDUCATIONAL_SUBJECTS = {
  HIGH_SCHOOL: HIGH_SCHOOL_SUBJECTS,
  UNIVERSITY: UNIVERSITY_SUBJECTS,
};

export function getSubjectsByLevel(level?: string) {
  if (level?.toUpperCase().includes("UNIVERSITY")) {
    return UNIVERSITY_SUBJECTS;
  }
  return HIGH_SCHOOL_SUBJECTS;
}
